import { MediaTrack } from './types';

export const DEFAULT_VLC_PLAYLIST: MediaTrack[] = [
  {
    id: 'sample_local_clip',
    title: 'Cyber Café 2004 Intro Reel (MP4)',
    url: '/samples/cyber_cafe_sample.mp4',
    type: 'sample',
    format: 'video',
    duration: 10,
    durationStr: '00:10',
    size: '1.1 MB',
    mimeType: 'video/mp4; codecs="avc1.42E01E, mp4a.40.2"',
    resolution: '1280x720',
    codec: 'H264 - MPEG-4 AVC (part 10) (avc1)',
    audioCodec: 'MPEG AAC Audio (mp4a)',
    audioChannels: 'Stereo',
    sampleRate: '44100 Hz',
    addedAt: 1,
  },
  {
    id: 'sample_mdn_stream',
    title: 'Mozilla CC0 High-Definition Stream (MP4)',
    url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
    type: 'network',
    format: 'video',
    duration: 10,
    durationStr: '00:10',
    size: '1.1 MB',
    mimeType: 'video/mp4',
    resolution: '1280x720',
    codec: 'H264 - MPEG-4 AVC',
    audioCodec: 'MPEG AAC Audio',
    audioChannels: 'Stereo',
    sampleRate: '44100 Hz',
    addedAt: 2,
  },
  {
    id: 'sample_somafm_radio',
    title: 'SomaFM Groove Salad (Live 24/7 Radio Stream)',
    url: 'https://ice1.somafm.com/groovesalad-128-mp3',
    type: 'network',
    format: 'audio',
    duration: 0,
    durationStr: 'LIVE',
    size: 'Continuous Stream',
    mimeType: 'audio/mpeg',
    codec: 'MPEG Audio layer 1/2/3 (mpga)',
    audioChannels: 'Stereo',
    sampleRate: '44100 Hz',
    addedAt: 3,
  },
  {
    id: 'sample_mdn_webm',
    title: 'Open Web Media Stream (WebM / VP8)',
    url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm',
    type: 'network',
    format: 'video',
    duration: 10,
    durationStr: '00:10',
    size: '554 KB',
    mimeType: 'video/webm',
    resolution: '640x360',
    codec: 'VP8 / Vorbis',
    audioCodec: 'Vorbis',
    audioChannels: 'Stereo',
    sampleRate: '44100 Hz',
    addedAt: 4,
  },
  {
    id: 'sample_local_audio',
    title: 'Midnight Cyber Café Audio Theme (MP3)',
    url: '/samples/retro_groove.mp3',
    type: 'sample',
    format: 'audio',
    duration: 5,
    durationStr: '00:05',
    size: '40 KB',
    mimeType: 'audio/mpeg',
    codec: 'MPEG Audio (mp3)',
    audioChannels: 'Stereo',
    sampleRate: '44100 Hz',
    addedAt: 5,
  },
];
